### ISSUE TITLE
Failed to build M2Crypto When installing adb==1.3.0

### ISSUE THREAD

**Issue by Ishu43642** [AKPR2007/ExposeMi#1]
~/ExposeMi $ pip install adb==1.3.0
Collecting adb==1.3.0
  Using cached adb-1.3.0-py3-none-any.whl               Collecting libusb1>=1.0.16 (from adb==1.3.0)              Using cached libusb1-3.0.0-py3-none-any.whl (62 kB)   Collecting M2Crypto<=0.26.4,>=0.21.1 (from adb==1.3.0)    Using cached M2Crypto-0.26.4.tar.gz (1.1 MB)            Installing build dependencies ... done
  Getting requirements to build wheel ... done            Preparing metadata (pyproject.toml) ... done
Collecting typing (from M2Crypto<=0.26.4,>=0.21.1->adb==1.3.0)
  Using cached typing-3.7.4.3-py3-none-any.whl          Building wheels for collected packages: M2Crypto
  Building wheel for M2Crypto (pyproject.toml) ... error  error: subprocess-exited-with-error
                                                          × Building wheel for M2Crypto (pyproject.toml) did not run successfully.                                        │ exit code: 1
  ╰─> [61 lines of output]                                    <string>:233: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
      running bdist_wheel
      running build                                           running build_py
      copying M2Crypto/BIO.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/m2urllib2.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/callback.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/DSA.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/Rand.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/ASN1.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/RSA.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/Engine.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/SMIME.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/AuthCookie.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/EC.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/X509.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/six.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/Err.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/threading.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/ftpslib.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/DH.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/RC4.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/httpslib.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/BN.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/m2.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/m2urllib.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/__init__.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/EVP.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/m2crypto.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/util.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      copying M2Crypto/m2xmlrpclib.py -> build/lib.linux-aarch64-cpython-311/M2Crypto
      creating build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      copying M2Crypto/PGP/PublicKey.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      copying M2Crypto/PGP/PublicKeyRing.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      copying M2Crypto/PGP/RSA.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      copying M2Crypto/PGP/packet.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      copying M2Crypto/PGP/constants.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      copying M2Crypto/PGP/__init__.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/PGP
      creating build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/Cipher.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/Checker.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/timeout.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/ssl_dispatcher.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/__init__.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/Context.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/Session.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/SSLServer.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/TwistedProtocolWrapper.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/cb.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      copying M2Crypto/SSL/Connection.py -> build/lib.linux-aarch64-cpython-311/M2Crypto/SSL
      running build_ext
      building 'M2Crypto._m2crypto' extension
      swigging SWIG/_m2crypto.i to SWIG/_m2crypto_wrap.c
      swig -python -D__aarch64__ -I/data/data/com.termux/files/usr/include/python3.11 -I/usr/include -I/usr/include/openssl -includeall -modern -builtin -outdir /data/data/com.termux/files/usr/tmp/pip-install-mr32_5rg/m2crypto_2fbab9865c584e0a91f035f3148cf6be/M2Crypto -o SWIG/_m2crypto_wrap.c SWIG/_m2crypto.i
      Deprecated command line option: -modern. Ignored, this option is now always on.
      SWIG/_m2crypto.i:43: Error: Unable to find 'openssl/opensslv.h'
      SWIG/_m2crypto.i:60: Error: Unable to find 'openssl/safestack.h'
      SWIG/_evp.i:12: Error: Unable to find 'openssl/opensslconf.h'
      SWIG/_rc4.i:5: Error: Unable to find 'openssl/opensslconf.h'
      SWIG/_ec.i:7: Error: Unable to find 'openssl/opensslconf.h'
      error: command '/data/data/com.termux/files/usr/bin/swig' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for M2Crypto
Failed to build M2Crypto
ERROR: Could not build wheels for M2Crypto, which is required to install pyproject.toml-based projects
~/ExposeMi $
![Screenshot_2023-06-10-07-16-36-914_com termux](https://github.com/AKPR2007/ExposeMi/assets/97582499/bde71635-49a9-4188-bd5a-302545ca6996)
![Screenshot_2023-06-10-07-16-28-905_com termux](https://github.com/AKPR2007/ExposeMi/assets/97582499/79ca6e6f-497f-4b06-a38c-9848b8aac195)

**Comment by ahmad24shargh** [comment]
swig not installed in termux by default

pkp install swig
...............

swig can not find openssl header files(The access path in Termox is different from Linux)
